# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: adminCARS
      POSTGRES_DB: CARSdb
      POSTGRES_PASSWORD: CARSdb123
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
